# Generated by Django 5.1.5 on 2026-02-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
