# Generated by Django 5.1.5 on 2026-02-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_joining_date_member_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='member',
            new_name='members',
        ),
    ]
